spring:
  datasource:
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/adzcmsot
    driver-class-name: org.postgresql.Driver
    username: adzcmsot
    password: Xd8xeYivybeEstts2UcLnhLFSkqt0YJg

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
            
feign:
  hystrix:
    enabled: true
