spring:
  datasource:
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/ftfeduyz
    driver-class-name: org.postgresql.Driver
    username: ftfeduyz
    password: ANtPSoA6bmxiZ19p4OsdCmKxKjOickHs

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update