spring:
  datasource:
    url: jdbc:postgresql://ec2-52-87-58-157.compute-1.amazonaws.com:5432/d9snov37aru577
    driver-class-name: org.postgresql.Driver
    username: gbtmzxckesiwwv
    password: 06cfbfa90dfe4124e4800e8be7aa35df2715dd8e56c860a4d199855c59b7a65b

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
            
feign:
  hystrix:
    enabled: true
